verbatim:
  cabal-version: 2.2

name: hook
version: 0.0.0.0

default-extensions:
  - ConstraintKinds
  - DataKinds
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MonadComprehensions
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - QuantifiedConstraints
  - RankNTypes
  - RebindableSyntax
  - ScopedTypeVariables
  - StandaloneDeriving
  - Strict
  - StrictData
  - TemplateHaskell
  - TypeApplications
  - TypeOperators
  - UndecidableInstances
  - UndecidableSuperClasses
  - UnicodeSyntax
  - ViewPatterns

ghc-options:
  - -Wall
  - -Wno-orphans
  - -O0
  - -j

executables:
  hook:
    source-dirs:
      - src
    main: Main.hs
    dependencies:
      - base
      - uvmhs
